services:

  release:
    image: node
    container_name: next_chat
    volumes:
      - ./:/usr/src/work/
    ports:
      - "3002:3002"
    working_dir: /usr/src/work/
    command: npm run build && npm run start

